<% require "dotenv"; Dotenv.load(".env") %>
service: <%= ENV['APP_NAME'] %>
image: "<%= ENV['KAMAL_REGISTRY_USERNAME'] %>/<%= ENV['APP_NAME'] %>"

servers:
  web:
    - <%= ENV['MAIN_HOST'] %>
  sidekiq:
    hosts:
      - <%= ENV['MAIN_HOST'] %>
    cmd: bundle exec sidekiq -C config/sidekiq.yml

builder:
  arch:
    - amd64
  args:
    RAILS_ENV: <%= ENV['RAILS_ENV'] %>
  cache:
    type: gha

readiness_delay: 10

proxy:
  app_port: 3000

registry:
  server: ghcr.io
  username: <%= ENV['KAMAL_REGISTRY_USERNAME'] %>
  password:
    - KAMAL_REGISTRY_PASSWORD

volumes:
  - /root/files:/rails/storage

env:
  clear:
    REDIS_URL: "redis://:<%= ENV['REDIS_PASSWORD'] %>@<%= ENV['REDIS_HOST'] %>:6379/1"
    RAILS_ENV: <%= ENV['RAILS_ENV'] %>
    DB_HOST: <%= ENV['DB_HOST'] %>
    HOST: <%= ENV['HOST'] %>
    RAILS_MAX_THREADS: <%= ENV['RAILS_MAX_THREADS'] %>
  secret:
    - POSTGRES_USER
    - POSTGRES_DB
    - POSTGRES_PASSWORD
    - RAILS_MASTER_KEY
    - SECRET_KEY_BASE

accessories:
  db:
    image: postgres:17
    host: <%= ENV['DB_HOST'] %>
    port: 5432
    env:
      secret:
        - POSTGRES_PASSWORD
        - POSTGRES_USER
        - POSTGRES_DB
    directories:
      - postgres:/var/lib/postgresql/data
    cmd: >
      postgres -c shared_preload_libraries=pg_stat_statements -c pg_stat_statements.max=5000 -c pg_stat_statements.track=all

  redis:
    image: redis:7.0.10
    host: <%= ENV['REDIS_HOST'] %>
    port: 6379
    cmd: redis-server --requirepass <%= ENV['REDIS_PASSWORD'] %>
    volumes:
      - /var/lib/redis:/data

logging:
  driver: journald
